### ISSUE TITLE
Bug Report: At any choice you take, when you press the back button from the device it brings you back to the home page of the app with single option unless you rotate the screen.

### ISSUE THREAD

**Issue by yusa55** [paceuniversity/gsd2014-team3#51] opened 2014-05-06 07:17 UTC
Environment: Android OS
Reporter: Yussuf
Steps to Reproduce the bug:
•  When the app is launched, click any linkable text from the given choice.
• Press the back button of your device.
Expected result: When it’s comes to the home page, all option should be available

Actual result: only the last option is seen as you just open the app

Priority: high

Severity: high

Screen Short:
![bug 7](https://cloud.githubusercontent.com/assets/6734865/2886776/6c7f38d8-d4ee-11e3-972d-d3c82bd571b4.jpg)

**Comment by jshor** [comment] 2014-05-10 20:21
Duplicate of #55

**Closed as completed by jshor** 2014-05-10 20:21 UTC
Labels: bug
